import Head from 'next/head'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  image: 'https://main--next-seo-test.netlify.app' + '/api/og',
  twitter: {
    handle: '@handle',
    site: '@site',
    cardType: 'summary_large_image',
    image: 'https://main--next-seo-test.netlify.app' + '/api/og',
  },
  // openGraph is for facebook and linkedin
  openGraph: {
    type: 'website',
    url: 'https://main--next-seo-test.netlify.app',
    title: 'rose fast food',
    description: 'we are aiming to provide the best food in the world',
    // image: 'https://main--next-seo-test.netlify.app' + '/api/og',
    image: 'https://main--next-seo-test.netlify.app/api/og',
    site_name: 'SiteName',
    locale: 'en_IE',
  },

}

export default function RootLayout({ children }) {
  const imageUrl =
  "https://main--next-seo-test.netlify.app" +
  '/api/og'

  return (
    <>
     
    <html lang="en">
    
      <body className={inter.className}>{children}</body>
    </html>
    </>
  )
}


